# External interface to reach the outside world
EXT_INTERFACE: eth0
EXT_NET_NAME: ext-net
EXT_SUBNET_NAME: ext-subnet
EXT_FLOATING_IP_START: 10.3.5.200
EXT_FLOATING_IP_END: 10.3.5.250
EXT_NETWORK_GATEWAY: 10.3.5.254
EXT_NETWORK_CIDR: 10.3.5.0/24

# Tunnel interface
TUN_INTERFACE: eth1

# Demo tenant name
DEMO_NET_NAME: demo-net
DEMO_SUBNET_NAME: demo-subnet
DEMO_GATEWAY: 172.30.11.254
DEMO_CIDR: 172.30.11.0/24
DEMO_ROUTER: demo-router
