- name: cinder service node packages
  apt: pkg={{ item }} state=installed
  tags: packages
  with_items:
    - lvm2

# the pv for cinder-volumes is hardcoded to /dev/sdb right now
- name: get if pv exists for sdb
  shell: pvs | grep sdb
  ignore_errors: true
  register: is_sdb_pv_exist

- name: create sdb pv
  shell: pvcreate /dev/sdb
  when: is_sdb_pv_exist.stdout == ''

- name: get if cinder-volumes vg exists
  shell: vgs | grep cinder-volumes
  ignore_errors: true
  register: is_cinder_volumes_vg_exist

- name: create cinder-volumes vg
  shell: vgcreate cinder-volumes /dev/sdb
  when: is_cinder_volumes_vg_exist.stdout == ''

- name: write lvm2 configuration
  template: src=lvm.conf.j2 dest=/etc/lvm/lvm.conf owner=root group=root mode=0644

- name: install cinder-volume
  apt: pkg=cinder-volume state=installed

- name: create cinder.conf
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf owner=root group=root mode=0644
  notify:
    - restart cinder-volume
    - restart tgt
