---
# file: site.yml

# A noop to trigger fact collection
- hosts: all
  tasks:
    - name: gtfo
      file: path=/etc/hosts state=touch
    - name: apt-get update
      apt: update_cache=yes
    - name: apt-get upgrade
      apt: upgrade=yes state=latest

- include: controller.yml
- include: network.yml
- include: compute.yml
