---

- name: keystone package
  apt: pkg=keystone state=installed
  tags: keystone

- name: write the keystone config file
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf owner=root group=root mode=0644
  notify:
    - restart keystone

- name: remove old sqlite db file
  file: path=/var/lib/keystone/keystone.db state=absent

- name: create keystone database
  mysql_db: name=keystone state=present

- name: keystone user from 127.0.0.1
  mysql_user: name=keystone password={{ KEYSTONE_DBPASS }} host='127.0.0.1' priv=keystone.*:ALL state=present

- name: keystone user from localhost
  mysql_user: name=keystone password={{ KEYSTONE_DBPASS }} host='localhost' priv=keystone.*:ALL state=present

- name: keystone user from %
  mysql_user: name=keystone password={{ KEYSTONE_DBPASS }} host='%' priv=keystone.*:ALL state=present

- name: remove localhost anonymous user
  mysql_user: name='' host='localhost' state=absent

- name: remove anonymous user with hostname
  mysql_user: name='' host={{ ansible_hostname }} state=absent

- name: keystone db_sync
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone
