---

- name: keystone package
  apt: pkg=keystone state=installed
  tags: keystone

- name: write the keystone config file
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf owner=root group=root mode=0644
  notify:
    - restart keystone

- name: remove old sqlite db file
  file: /var/lib/keystone/keystone.db state=absent
