- name: Mysql | Set root password
  shell: debconf-set-selections <<< 'mysql-server mysql-server/root_password password {{ MYSQL_ROOT_PASS }}'

- name: Mysql | Set root repassword
  shell: debconf-set-selections <<< 'mysql-server mysql-server/root_password_again {{ MYSQL_ROOT_PASS }}'
