---

- name: nova package
  apt: pkg={{ item }} state=installed
  tags: nova
  with_items:
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy
    - nova-scheduler
    - python-novaclient
    
